# Bliss optimizations
WITH_BLISS_CHARGER := false
TARGET_PC_BUILD := true

# Bliss OS specific 
RELEASE_OS_TITLE := Bliss-OS
BLISS_BUILD := Bliss-OS
BUILD_NAME_VARIANT := Bliss-OS 
BLISS_VERSION_MAINTENANCE := Alpha-Dev
BLISSIFY := true
BLISS_GRAPHITE := true
BLISS_STRICT := false
FLOOP_NEST_OPTIMIZE := true
BLISS_PIPE := true
BLISS_GOMP := true
BLISS_EXTRAGCC := true
FAST_MATH := true
LINK_TIME_OPTIMIZATIONS := true
